version: '3.7'
services:
  haproxy_panel_next:
    restart: always
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run start-dev
    volumes:
      - type: bind
        source: /tmp/acme-tests/.well-known/acme-challenge/
        target: /tmp/acme-tests/.well-known/acme-challenge/
      - type: bind
        source: ./ca/
        target: /opt/ca/
  haproxy_panel_mongo:
    restart: always
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
networks:
  default:
    name: haproxy_panel_next
volumes:
  mongodb_data_container:
